baseURL = "https://vghpe.github.io/blog/"
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
theme = 'mini'
[params]
hiddenPostSummaryInHomePage = false 
copyright = "Â© 2024 Henrik Pettersson. All rights reserved."
showPowerBy = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Fluff"
  url = "/fluff/"
  weight = 2
